### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by orelh** [mthyden/PhillipsHueSIMPLSharp#17]
Getting the following when I try to control either room:
00:03:14.299: [User Stimulus] : User set Hue_Room3_Raise to Press
00:03:14.346: Hue_Room3_Raise -> 1
00:03:14.362: [Console Data] : Exception is System.ArgumentOutOfRangeException: 
00:03:14.362: [Console Data] : Parameter name: index
00:03:14.362: [Console Data] :    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
00:03:14.362: [Console Data] :    at System.Collections.Generic.List`1.get_Item(Int32 index)
00:03:14.362: [Console Data] :    at HueLights.HueRoom.LightsVal(String lvltype, UInt16 val)
00:03:14.362: [Console Data] :    at UserModule_HUELIGHTSROOM_R1_5.UserModuleClass_HUELIGHTSROOM_R1_5.ROOMBRIIN_OnChange_7(Object __EventInfo__)
00:03:14.362: [Console Data] :    at Amib.Threading.Internal.WorkItem.n()
00:03:14.362: [Console Data] :    at Amib.Threading.Internal.WorkItem.Execute()
00:03:14.362: [Console Data] :    at Amib.Threading.SmartThreadPool.f(WorkItem A_0)
00:03:14.362: [Console Data] :    at Amib.Threading.SmartThreadPool.r()
00:03:14.362: [User Stimulus] : User set Hue_Room3_Raise to Release

**Comment by mthyden** [comment]
listing just an exception isn't very helpful in troubleshooting what your issue is. if you send me your bridge data in JSON format for bulbs, groups, and scenes, I can take a look in my offline utility.  instructions https://developers.meethue.com/develop/get-started-2/

I did just post an update which should work around bridge irregularities if the bulbs/groups are not sequential which is rare but does occur when rooms are added, deleted and then re-added sometimes.
