### ISSUE TITLE
Weird issue polling bulbs.

### ISSUE THREAD

**Issue by innocuoussoul** [mthyden/PhillipsHueSIMPLSharp#2]
<img width="620" alt="error" src="https://cloud.githubusercontent.com/assets/7485783/26281000/c7730f5c-3d9c-11e7-95de-c437af1a33bc.png">

used debugger to grab api key, but now, any time it polls for bulbs I get this error. Rooms and Scenes don't seem to produce an error either. All the rooms when triggered use group0 and turn off all the lights (or turn them on.

**Comment by mthyden** [comment]
Are you using the original or the 1.1 proc module? Does the proc module report Online after the init sequence? does the API key string output on the module show your API key? Possible I’ve introduced a timing issue where a null somehow is being injected into the bulb request but haven’t seen that on my system unless its due to the number of bulbs. I usually put about 10 sec or more after the program has settled then trigger the init on the proc module.

Feel free to provide me the JSON response from the bulb query using their API testing utility on the bridge:

http://<bridge ip address>/debug/clip.html
/api/<username>/lights
username is your APIKey

**Comment by innocuoussoul** [comment]
Using 1.1, had to pull from the archive because your uploaded smw is invalid/corrupted

API Key was successfully gathered and stored according to crestron toolbox. 
Using SIMPL Debugger and running hue_refresh is when it fails. 
bulbs files with the error above, and then Rooms/Scenes stay empty. 

I have a lot of bulbs, so here's the first two. 
```
{
	"4": {
		"state": {
			"on": true,
			"bri": 254,
			"hue": 15335,
			"sat": 121,
			"effect": "none",
			"xy": [
				0.4448,
				0.4066
			],
			"ct": 343,
			"alert": "none",
			"colormode": "xy",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Kitchen 1",
		"modelid": "LCT007",
		"manufacturername": "Philips",
		"uniqueid": "xxxxxxxx",
		"swversion": "5.50.1.19085"
	},
	"7": {
		"state": {
			"on": true,
			"bri": 254,
			"alert": "none",
			"reachable": true
		},
		"type": "Dimmable light",
		"name": "Kitchen 4",
		"modelid": "LWB006",
		"manufacturername": "Philips",
		"uniqueid": "xxxxxxxx",
		"swversion": "5.38.2.19136"
	},



```

**Comment by mthyden** [comment]
what is “a lot of bulbs” I only have 6 so its possible its due to the number of bulbs however the largest deployment I’ve done with the original modules was 29 total bulbs. The new 1.1 doesn’t change how the bulb request happens but I did adjust some timing of when the calls occur.

You don’t need to do anything with hue_refresh to get it working that's just a secondary polling routine if bulbs/rooms/scenes change after the init process is complete. So your saying its failing during the init. What kind of delay do you have after program start before you trigger init?

I have the JSON from the site with the 29 bulbs so can run it through the new modules to see if it fails other then that there may be something else at play as it works on my end. Like I said before if you provide the entire complete JSON bulb data I can run it through on my end to see if something is unique with your particular bulbs. I have a mix of 2nd and 3rd gen some color some white only so it should be flexible enough to trap everything.

**Comment by innocuoussoul** [comment]
[bulbs.txt](https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1023202/bulbs.txt)
I'm somewhere around 25 bulbs. Almost all of them should be Philips bulbs, with a mix of white and color bulbs. the only "bulbs" that aren't bulbs are my led strips, those are 3rd party. Those are bulbs 21,22

**Comment by mthyden** [comment]
Thanks for the bulbs.txt file that helped. I believe I see whats going on. Its related to the bulb ID, not so  much the misordering of them but the fact that you have omissions in the sequential list. I think this occurs when bulbs have been added/removed then added again to a bridge. I will need to restructure my query logic to compensate.

**Comment by mthyden** [comment]
I’ve pushed an update that should resolve the issues you were seeing. I modified the bulb/room/scenes query to be more flexible and forgiving. All you should need to do is replace your old CLZ with the new one. then recompile all.

**Comment by innocuoussoul** [comment]
The only changes i've made to your files is that I have a CP3, not a CP3N. other than that and the touchpanel, nothing is different than your default stuff.  

<img width="623" alt="exception" src="https://cloud.githubusercontent.com/assets/7485783/26485916/ba6ced22-41ad-11e7-8a02-6942858435a9.PNG">

**Comment by mthyden** [comment]
The first exception is benign, I’ve seen it throw right after a program load in the init process but doesn’t affect the runtime. If you manually pulse the init after the program settles you most likely won’t see it which makes me think its a timing thing which I’m looking into. Regardless. The second one I don’t know as you haven’t provided any details except for a debug output. My suggestion would be to manually trigger the init on the main proc module first see the result, also crack open the Proc UMC and massage the stepper init in there which governs when the bridge is grabbed, registration and getting bulbs, groups, scenes.

**Comment by mthyden** [comment]
curious if your still running into problems, the new polling routines should work for you at this point
