### ISSUE TITLE
Crestron Database 200.xxx.xxx

### ISSUE THREAD

**Issue by kjevat** [mthyden/PhillipsHueSIMPLSharp#29]
Hi
I had trouble using this module once I updated to Crestron Database 200.x
This is a common problem and all previous c# modules needs to recompile.
Is this something you can do?

Thanks :-)

**Comment by mthyden** [comment]
Negative the DeviceDB update would not have affected my modules. I authored these libraries with the SimplSharpNewtonsoft library which wasn’t affected with that library update. The library that was impacted by the Device DB update was the Newtonsoft.json.compact which I never use in my libraries as it has always had issues compared to the SimplSharpNewtonsoft one.

I’m using the current release Device/Crestron DBs and haven’t had an issue with the JSON serializing/deserializing. I have noticed there may be an issue with the processor discovery which would be unrelated however if you hardcode the Bridge IP the issue is mitigated.

What specifically are you having issues with? The only other outstanding issue which I am working on is adding saturation level support for the Hue bulbs that don’t support color but do allow for the white temp change.

**Comment by mthyden** [comment]
You may have been right that an underlying simplsharp SDK implementation was using the older Newtonsoft libraries, I normally only vouch for the libraries I directly utilize but noticed when I was working on the CT feature add that the newtonsoft.compact was still being outputted, anyway, its all been recompiled and tested against 4-series so pull down the latest. Apologies for the confusion.

**Comment by kjevat** [comment]
Thank you for the update. I did revert back to the old database and was able to get it working again.
But I will try your new version and update database again the next days. Other than this DB issue your modules have been rock solid for about 20+ lights for a half year now. :-)

**Comment by kjevat** [comment]
I can confirm that the new version from yesterday now works with the crestron database 200.xxx.xxx
Thank you for this fast update!
