### ISSUE TITLE
NullReferenceException in XY color select

### ISSUE THREAD

**Issue by ir0n87** [mthyden/PhillipsHueSIMPLSharp#32]
Here the error message I receive when i try to set a colour with XY image.
Sometimes colour change but 99% of times i receive this error...

![XY](https://user-images.githubusercontent.com/40760225/111187885-c1628980-85b4-11eb-92cc-b73ac171798f.PNG)

Thanks!

**Comment by mthyden** [comment]
thanks for reporting, I'll look into it this week

**Comment by ir0n87** [comment]
Any news? many thanks!

**Comment by mthyden** [comment]
Apologies for the delay, paying work got in the way ;)

I’ll be able to look into this tomorrow.

**Comment by mthyden** [comment]
Duplicated the exception being thrown in console, however the lights 100% of the time will always change.. through my xpanel with the XY graph I have in my demo program. I can clean up the exception however you mentioned it wasn’t changing lights some of the time. In my test I mouse clicked on different XY points on my graph with about .5 sec precision which resulted in the lights changing 100%, I’m assuming you have the XYs on some sort of slider or another mechanism.

I know the traditional color slider works at that fast rate but more testing would need to determine if the XY has that level of responsiveness.

What is your use case here?

**Comment by ir0n87** [comment]
I'm using RMC3 as processor (also tried on MC3).
I've loaded your project with your graphic.
When i click con XY colour, it changes only sometimes. When colour change the exception error does not came out.

**Comment by mthyden** [comment]
Interesting, the last rev I haven’t tested on 3-series, been only testing on 4-series. That being said when I dev’d this feature it was working without issue on 3-series. I suspect it may be related to timing since my requests to the bridge are returned in the same method which is not ideal for REST APIs, I have been looking at restructuring all of the requests and cmds to event purely event based. However that’s a lot of work and I’m waiting on Crestron to release an update to Crestron Home that includes support for third party lighting eco-systems as I intend on modifying this implementation for Crestron Home Extensions. I may do a test migrating the XY request recall to a HTTPAsync method to see if that alleviates the issue on a 3-series and resolves the exception on 4-series however if it doesn’t I’m most likely going to wait till I can start work on the Crestron Home Extensions and not address this issue until then. I’ll let you know.

**Comment by mthyden** [comment]
I should be able to post an update on Sunday. The coding is complete but I have to do quite a bit of testing as it was a significant effort refactoring the event mechanisms under the hood, but so far its look promising. I will run through some minimal tests on the 3-series side. This effort needed to happen for the Crestron Extensions support I’m working on.

**Comment by mthyden** [comment]
Just posted an updated demo pgm for 3/4series with the fix. Tested on a PRO3 and MC4. I am confident your RMC3 will be fine as well, MC3 is a slightly different beast so will not vouch for that platform. The modules and pgm are the same all you really need to replace is the CLZ

**Comment by ir0n87** [comment]
Wonderful JOB!
Many thanks!
