### ISSUE TITLE
Bug with rooms

### ISSUE THREAD

**Issue by leissnerj** [mthyden/PhillipsHueSIMPLSharp#8]
Hi again.

I've found a bug and the cause of it.

I had deleted one room in my hue app, however that doesn't change the associated room numbers.
According to my hue logs I have rooms
1: Living room
3: Bedroom
4: Office
5: Kitchen

When using the modules right now that generated an empty room, when you try to control it, it'll control all the lamps in the house.
![huebugg](https://user-images.githubusercontent.com/32220771/32408731-386e7eaa-c19e-11e7-8c57-64499b6e94b1.PNG)

I sorted it by making a new room and moving around some lamps.

**Comment by leissnerj** [comment]
Oh, and any chance you'll integrate the hue motions sensors? Would love to have their feedback in the proc

**Comment by mthyden** [comment]
I’ve deleted rooms and re-inited and haven’t see that issue, you may want to pull your bridge data to see if the room is ghosted in the bridge list, I’m beginning to realize that the bridge data is not the same as what the hue app must maintain itself as I’ve seen other bridge related defects in their data, I’ll try some room adds and deletions to see if I can reproduce but again suspect it’s the bridge data itself.

**Comment by mthyden** [comment]
Yeah totally, I’ve been thinking of adding support for them and some other accessories, I’ll probably need to add a queuing routine to the bridge requests as polling will need to be incorporated I assume to get motion sensor info, I’ll look into it this week

**Comment by leissnerj** [comment]
Fairly certain this is exactly how I caused the error.

I had Hallway as my number 2 room, but I moved that lamp to the living room (number one) and deleted hallway. So the room with the id 2 was missing,

When I fixed the error I created a new room, and that new room was placed between Living room and bedroom, at id 2. and rearranged the loads accordingly. Working like a charm now.

I'm in the process of setting up a raspberry with homebridge to act as a gateway to get siri commands over to crestron, was thinking about using that gateway to push the motion sensor data aswell. But would be great to see that supported in your modules.

**Comment by mthyden** [comment]
I’ll definitely look into the room deletion thing, not sure how that could happen in my framework since I completely wipe the existing datas structures in my modules and re-populate only from the data in the bridge. Like I said, I’ve seen weird bridge data though with scenes without loads associated and even duplicates scenes in the bridge data but I’ll dig deeper, in a defective state can you provide me the Rooms and scenes get data? that would help me identify the issue.

I’ll see what I can do about the motion sensor support, may not be too difficult to throw in quickly.

The Raspberry homebridge thing is pretty slick, I’m investigating a native Crestron homekit solution.


On Nov 5, 2017, at 3:45 PM, leissnerj <notifications@github.com> wrote:

Fairly certain this is exactly how I caused the error.

I had Hallway as my number 2 room, but I moved that lamp to the living room (number one) and deleted hallway. So the room with the id 2 was missing,

When I fixed the error I created a new room, and that new room was placed between Living room and bedroom, at id 2. and rearranged the loads accordingly. Working like a charm now.

I'm in the process of setting up a raspberry with homebridge to act as a gateway to get siri commands over to crestron, was thinking about using that gateway to push the motion sensor data aswell. But would be great to see that supported in your modules.

**Comment by mthyden** [comment]
Any chance you have one of the Hue Motion sensors in your system? I have a couple of the dimmer switches, and I just ordered a tap and a motion sensor which I should get later this week. 

/api/<username>/sensors

If you do, I was hoping you could provide me the sensor JSON request data so I can begin working on adding sensors.

Initially I plan to support the three Zigbee based ones
Hue Tap - ZGPSwitch
Hue Wireless Dimmer Switch - ZLLSwitch
Hue Motion Sensor - ZLLPresence

I plan on keeping this project Hue specific so I don’t plan on supporting CLIP sensors and switches at this time.

On Nov 5, 2017, at 3:45 PM, leissnerj <notifications@github.com> wrote:

Fairly certain this is exactly how I caused the error.

I had Hallway as my number 2 room, but I moved that lamp to the living room (number one) and deleted hallway. So the room with the id 2 was missing,

When I fixed the error I created a new room, and that new room was placed between Living room and bedroom, at id 2. and rearranged the loads accordingly. Working like a charm now.

I'm in the process of setting up a raspberry with homebridge to act as a gateway to get siri commands over to crestron, was thinking about using that gateway to push the motion sensor data aswell. But would be great to see that supported in your modules.

**Comment by leissnerj** [comment]
Sure

Attaching my groups and scenes in txt format, However I've fixed the issue by now.
Also adding the sensors json data aswell sensor nr 6 json data, that's the actual motion sensor. The presence value turns true when it triggers.

You also get an extra bonus of a temperature sensor, since the motion detector is PIR sensor.
[scenes 2.txt](https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1447937/scenes.2.txt)
[groups 2.txt](https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1447938/groups.2.txt)
[sensor.zip](https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1447943/sensor.zip)

Github doesn't support uploaded Json so I added them to a zip.

**Comment by mthyden** [comment]
perfect thanks

On Nov 6, 2017, at 3:12 PM, leissnerj <notifications@github.com> wrote:

Sure

Attaching my groups and scenes in txt format, However I've fixed the issue by now.
Also adding the sensors json data aswell sensor nr 6 json data, that's the actual motion sensor. The presence value turns true when it triggers.

You also get an extra bonus of a temperature sensor, since the motion detector is PIR sensor.
scenes 2.txt <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1447937/scenes.2.txt>
groups 2.txt <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1447938/groups.2.txt>
sensor.zip <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1447943/sensor.zip>
Github doesn't support uploaded Json so I added them to a zip.

**Comment by leissnerj** [comment]
Here's a video showcasing homekit taking control of the hue tap. Don't know if it's helpful, but an interesting thing is that the hue bridge recognizes that something is overwriting it's control.
https://youtu.be/8NnQFjuGSBY?t=55s

**Comment by mthyden** [comment]
I'm closing this as I have not heard back, the sensor feature request is on hold, I added some plumbing the project that does pull down sensor data however since each individual sensor type tied to a single motion sensor comes in as separate items I'm trying to determine the best way to determine who belongs to who if multiple motion sensors are in play.
